
version: "3"
services:
  db:
    image: mysql:latest
    container_name: mysql
    platform: linux/x86_64

    volumes:
     - type: volume
        source: hackathon_mysql
        target: /var/lib/mysql
      - type: bind
        source: ./init
        target: /docker-entrypoint-initdb.d

    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hackathon
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      LC_ALL: C.UTF-8
