CREATE TABLE user (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  bio CHAR(255),
  img CHAR(255),
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE message (
  id CHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  postedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  postedBy CHAR(36) NOT NULL,
  channelId CHAR(36) NOT NULL,
  edited BOOLEAN NOT NULL DEFAULT FALSE,
  deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE reply (
  id CHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  postedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  postedBy CHAR(36) NOT NULL,
  replyTo CHAR(36) NOT NULL,
  edited BOOLEAN NOT NULL DEFAULT FALSE,
  deleted BOOLEAN NOT NULL DEFAULT FALSE
);